#!/bin/bash
# 
# 生成index文件列表
# 

files=$(find ./[0-9a-z_]*)
index_filename='0-index.md'
echo '## 文章目录' > $index_filename
echo '' >> $index_filename

for p in $files
do
    f=${p##*/}
    num=$(echo $p | awk -F'/' '{print NF-1}')
    num=$[($num-1)*2+1]
    spaces=$(seq -s' ' $num | tr -d '[0-9]')
    echo $num:"$spaces"$p
    if [ -d $p ]
    then
        # 输出目录
        echo "$spaces"'- '$f >> $index_filename
    elif [ -f $p -a 'md' = ${f##*.} -a 'README' != ${f%.*} ] 
    then
        # 输出文件
        title=$(head -n 1 $p|sed 's/^#*\s*//'|sed 's/\s*$//')
        [ ${#title} -lt 2 ] && title=${p%.*}
        echo "$spaces"'- ['$title'](https://github.com/IBBD/blog/tree/master/'${p:2}')' >> $index_filename
    fi
done

echo '====> finish!'
